Repository whs2iso/Forensic, pull requests merged in 2024-05, with the labels that each got.

#11 Kimseoyoung - Enc-JPG/Suninatas19, 28
  disk_forensics/[Enc-Jpg]Write-up.pdf
  disk_forensics/[Suninatas 28]Write-up.pdf
  other_forensics/[Suninatas 19]Write-up.pdf
Labels: done

#20 Yoon jiwon - Sleepingshark, suninatas 21, 26
  multimedia_forensics/[Suninatas 21] Write-Up.pdf
  network_forensics/[Sleepingshark] Write-Up.pdf
  other_forensics/[Suninatas 26] Write-Up.pdf
Labels: done

#6 Heo eun jung - Brothers/PDF Analysis/Terrorist
  disk_forensics/[PDF Analysis]Write-Up.pdf
  disk_forensics/[Terrorist]Write-Up.pdf
  other_forensics/[Brothers]Write-Up.pdf
Labels: done

#7 ParkHyeMi - FFFFAAAATTT/lolololologfile/Military
  disk_forensics/[FFFFAAAATTT] Write-Up.pdf
  disk_forensics/[lolololologfile] Write-Up.pdf
  memory_forensics/[Military] Write-Up.pdf
Labels: done

#15 RyuNaYeon - suninatas 14,15,18
  disk_forensics/[evidence]Write-Up.pdf
  multimedia_forensics/[diary]Write-Up.pdf
  other_forensics/[suninatas-18]Write-Up.pdf
Labels: done

#27 Kimkyeongmin2 - Deleted file/ZIP/memorry dummppp
  disk_forensics/[Deleted file]WriteUp.pdf
  disk_forensics/[ZIP]WriteUp.pdf
  memory_forensics/[Memoryyyyy Dumpppppp]WriteUp.pdf
Labels: final

#31 Kimkyeongmin2 - Snowing!/palm/video_in_video
  multimedia_forensics/[Snowing!]WriteUp.pdf
  multimedia_forensics/[video_in_video]WriteUp.pdf
  network_forensics/[palm]WriteUp.pdf
Labels: final

#32 Kimkyeongmin2 - Deleted file/Zip/Memoryyyyy Dumpppppp
  disk_forensics/[Deleted file]WriteUp.pdf
  disk_forensics/[ZIP]WriteUp.pdf
  memory_forensics/[Memoryyyyy Dumpppppp]WriteUp.pdf
Labels: final

#25 Park Hye Mi - Ann's AppleTV/Ann's Aurora/Ann's Dark Tangent
  network_forensics/[Ann’s AppleTV] Write-Up.pdf
  network_forensics/[Ann’s Aurora] Write-Up.pdf
  network_forensics/[Ann’s Dark Tangent] Write-Up.pdf
Labels: final

#23 Heo Eun Jung - Paint/Cat/LineFeed/Art
  disk_forensics/[Art]Write-Up.pdf
  multimedia_forensics/[LineFeed]Write-Up.pdf
  multimedia_forensics/[Paint]Write-Up.pdf
  multimedia_forensics/[cat]Write-Up.pdf
Labels: final

#22 Shim ju wan - File Deleted/Whos Notebook/Dream Zoo
  disk_forensics/[File Deleted] Write-Up.pdf
  disk_forensics/[Whos Notebook] Write-Up.pdf
  disk_forensics/[Windows Search] Write-Up.pdf
  multimedia_forensics/BMP_Recovery/[BMP-Recovery] Write-Up.pdf
  multimedia_forensics/BMP_Recovery/recover.py
  multimedia_forensics/[Basic_Forensics_1] Write-Up.pdf
  network_forensics/[Dream Zoo] Write-Up.pdf
Labels: final

#37 Revert - [Deleted file][Zip][Memoryyyyy Dumpppppp]
  disk_forensics/[Deleted file]WriteUp.pdf
  disk_forensics/[ZIP]WriteUp.pdf
  memory_forensics/[Memoryyyyy Dumpppppp]WriteUp.pdf
Labels: help

#43 Kim seoyoung - Enc-JPG/Suninatas 19/Suninatas 28
  disk_forensics/[Enc-Jpg]Write-up.pdf
  disk_forensics/[Suninatas 28]Write-up.pdf
  other_forensics/[Suninatas 19]Write-up.pdf
Labels: final

#46 Kimkyeongmin2 - palm/Snowing!/video_in_video
  multimedia_forensics/[Snowing!]WriteUp.pdf
  multimedia_forensics/[video_in_video]WriteUp.pdf
  network_forensics/[palm]WriteUp.pdf
Labels: final

#47 Ryunayeon - Suninatas 14,15,18
  multimedia_forensics/[Suninatas-14] WriteUp.pdf
  other_forensics/[Suninatas-14] WriteUp.pdf
  other_forensics/[Suninatas-18] Write-Up.pdf
Labels: final

#49 Shim ju wan - Find the cat, DFC-2021 -302, DFC-2022-104
  system_forensics/[DFC-2021-302] Write-Up.pdf
  system_forensics/[Find the cat] Write-Up.pdf
Labels: final
